nfs:
  # The IP address of the OMV NAS
  server: 192.168.1.253
  # The absolute path we configured in OMV (relative to /export/ for NFS)
  path: /export/KubernetesLogs

storageClass:
  # We name the StorageClass 'nfs-client'
  name: nfs-client
  # Make it the default storage class for the cluster
  defaultClass: true
  
  # Ensure reclaimed volumes are kept on the NAS but archived instead of deleted
  reclaimPolicy: Retain
  archiveOnDelete: true
