apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi # This must be less than or equal to the PV's capacity
  storageClassName: ""
